import json
from pathlib import Path

import click
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TextColumn,
    TimeElapsedColumn,
    TimeRemainingColumn,
)

from hysail.hysail_decode import HysailDecode
from hysail.hysail_encode import HysailEncode
from hysail.chain import HysailChainPublisher, build_file_manifest
from hysail.chain.publisher import load_file_registry_address
from hysail.encryption.encoding_metadata import EncodingMetadata
from hysail.logger.progress import set_progress
from hysail.utils.debug import set_debugging


def _create_progress() -> Progress:
    return Progress(
        SpinnerColumn(),
        "[progress.description]{task.description}",
        BarColumn(),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        TimeRemainingColumn(),
    )


def _define_debug_time_flag(debug_time):
    if debug_time:
        set_debugging(True)


@click.group()
def main():
    pass


@main.command("encode")
@click.argument("input_file", type=click.Path(exists=True))
@click.option(
    "--block-size",
    type=int,
    default=None,
    help="Block size for encoding; if omitted, uses 10% of the file size",
)
@click.option(
    "--server-list",
    type=click.Path(exists=True),
    required=True,
    help="JSON file with server list schema: {'servers': [{'id': <number>, 'storage_location': <location>}, ...]}",
)
@click.option(
    "--metadata-output",
    type=click.Path(),
    default="./",
    show_default=True,
    help="Path where the metadata file will be written",
)
@click.option(
    "--debug-time",
    is_flag=True,
    help="Enable timing of key operations for performance analysis (also set DEBUG_TIME env var)",
)
def encode_command(input_file, block_size, server_list, metadata_output, debug_time):
    with open(server_list, "r") as f:
        data = json.load(f)
    servers = data["servers"]

    _define_debug_time_flag(debug_time)

    with _create_progress() as progress:
        set_progress(progress)
        hysail_encode = HysailEncode(input_file, block_size, servers, metadata_output)
        packet_count = hysail_encode.encode()
        set_progress(None)

    click.echo(f"Encoded {packet_count} packets distributed to {len(servers)} servers")


@main.command("decode")
@click.argument("metadata_file", type=click.Path(exists=True))
@click.option(
    "--server-file",
    type=click.Path(exists=True),
    required=True,
    help="JSON file with server information for decoding",
)
@click.option(
    "--output-file",
    type=click.Path(),
    default="./",
    show_default=True,
    help="Path where the decoded file will be written",
)
@click.option(
    "--debug-time",
    is_flag=True,
    help="Enable timing of key operations for performance analysis (also set DEBUG_TIME env var)",
)
def decode_command(metadata_file, server_file, output_file, debug_time):
    _define_debug_time_flag(debug_time)

    with _create_progress() as progress:
        set_progress(progress)
        hysail_decode = HysailDecode(metadata_file, server_file, output_file)
        output_path = hysail_decode.decode()
        set_progress(None)

    click.echo(f"Decoded file written to {output_path}")


@main.command("publish")
@click.argument("metadata_file", type=click.Path(exists=True))
@click.option(
    "--metadata-uri",
    required=True,
    help="URI that points to the metadata or manifest served to DApp consumers",
)
@click.option(
    "--deployment-file",
    type=click.Path(exists=True),
    default=None,
    help="JSON file generated by the DApp deploy script containing the fileRegistry address",
)
@click.option(
    "--contract-address",
    default=None,
    help="Override the fileRegistry address instead of loading it from a deployment file",
)
@click.option(
    "--rpc-url",
    default="http://127.0.0.1:8545",
    show_default=True,
    help="Ethereum JSON-RPC URL",
)
@click.option(
    "--private-key",
    envvar="HYSAIL_CHAIN_PRIVATE_KEY",
    default=None,
    help="Private key used to sign the registerFile transaction",
)
@click.option(
    "--file-id",
    default=None,
    help="Optional human-readable file id. If omitted, HySail derives one from the metadata",
)
@click.option(
    "--manifest-output",
    type=click.Path(),
    default=None,
    help="Optional path where the generated chain manifest JSON will be written",
)
def publish_command(
    metadata_file,
    metadata_uri,
    deployment_file,
    contract_address,
    rpc_url,
    private_key,
    file_id,
    manifest_output,
):
    if not private_key:
        raise click.ClickException(
            "Provide --private-key or set HYSAIL_CHAIN_PRIVATE_KEY"
        )

    resolved_contract_address = contract_address
    if resolved_contract_address is None:
        if deployment_file is None:
            raise click.ClickException(
                "Provide --deployment-file or --contract-address"
            )
        resolved_contract_address = load_file_registry_address(deployment_file)

    metadata = EncodingMetadata.load(Path(metadata_file))
    manifest = build_file_manifest(metadata, metadata_uri, file_id=file_id)

    resolved_manifest_output = (
        Path(manifest_output)
        if manifest_output
        else Path(metadata_file).with_name(
            f"{Path(metadata_file).stem}_chain_manifest.json"
        )
    )
    resolved_manifest_output.write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )

    publisher = HysailChainPublisher(rpc_url, resolved_contract_address, private_key)
    receipt = publisher.publish_manifest(manifest)

    click.echo(
        "Published file "
        f"{receipt['fileId']} to {receipt['contractAddress']} "
        f"in tx {receipt['transactionHash']}"
    )
    click.echo(f"Chain manifest written to {resolved_manifest_output}")


if __name__ == "__main__":
    main()
